[package]
name = "kekano"
version = "0.1.0"
authors = ["Simon Bergström <simon@menuan.se>"]
edition = "2018"

[dependencies]
image = "0.21"
vulkano = "0.13"
vulkano-shaders = "0.13"
vulkano-win = "0.13"
winit = "0.19"